# Generated by Django 5.1 on 2025-02-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customer_user_remove_farmer_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customerprofile',
        ),
        migrations.RenameModel(
            old_name='Farmer',
            new_name='farmerprofile',
        ),
    ]
