# Generated by Django 5.1 on 2025-02-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_farmerprofile_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='confirm_password',
        ),
    ]
